### ISSUE TITLE
[SQLite] java.lang.ArrayIndexOutOfBoundsException on batch insert with DAO

### ISSUE THREAD

**Issue by dancing-koala** [JetBrains/Exposed#1144] opened 2021-01-21 09:59 UTC
> exposed: 0.28.1
> kotlin: 1.4.21
> sqlite driver: 3.30.1 (org.xerial:sqlite-jdbc)
> sqlite: 3.34.0

Hi, when I try to insert 2 objects in one transaction using Exposed DAO I get a java.lang.ArrayIndexOutOfBoundsException because of the batch insert.

Inserting mutliple objects using DAO only works when using one transaction per insert.

Here is the full stacktrace:

```
java.lang.ArrayIndexOutOfBoundsException: 12
	at org.sqlite.core.CorePreparedStatement.batch(CorePreparedStatement.java:130)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.setObject(JDBC3PreparedStatement.java:388)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.set(JdbcPreparedStatementImpl.kt:26)
	at org.jetbrains.exposed.sql.IColumnType$DefaultImpls.setParameter(ColumnType.kt:64)
	at org.jetbrains.exposed.sql.ColumnType.setParameter(ColumnType.kt:71)
	at org.jetbrains.exposed.sql.statements.api.PreparedStatementApi$DefaultImpls.fillParameters(PreparedStatementApi.kt:13)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.fillParameters(JdbcPreparedStatementImpl.kt:9)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:53)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:129)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:115)
	at org.jetbrains.exposed.sql.statements.Statement.execute(Statement.kt:29)
	at org.jetbrains.exposed.sql.QueriesKt.batchInsert(Queries.kt:137)
	at org.jetbrains.exposed.sql.QueriesKt.batchInsert$default(Queries.kt:92)
	at org.jetbrains.exposed.dao.EntityCache.flushInserts$exposed_dao(EntityCache.kt:112)
	at org.jetbrains.exposed.dao.EntityCache.flush(EntityCache.kt:80)
	at org.jetbrains.exposed.dao.EntityCache.flush(EntityCache.kt:49)
	at org.jetbrains.exposed.dao.EntityCacheKt.flushCache(EntityCache.kt:154)
	at org.jetbrains.exposed.dao.EntityLifecycleInterceptor.beforeCommit(EntityLifecycleInterceptor.kt:40)
	at org.jetbrains.exposed.sql.Transaction.commit(Transaction.kt:63)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:171)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:211)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:219)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:210)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:148)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:219)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:120)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:118)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:117)
	at com.dancing_koala.repository.DatabaseAccountRepositoryTest.setUp(DatabaseAccountRepositoryTest.kt:44)
```

The code causing this exception:

```kotlin
  Database.connect(...)

  transaction {
      addLogger(StdOutSqlLogger)
      SchemaUtils.create(*tables) // tables is an array of table classes

      // activeAccount & disabledAccount are POKO objects
      arrayOf(activeAccount, disabledAccount).forEach {
          AccountEntity.new {
              identity = it.identity
              name = it.name
              hashedPassword = it.hashedPassword
              created = it.created
              updated = it.updated
              disabled = it.disabled
          }
      }
  }
```

This code is used in a Test class but runs & crashes before launching any test.

Thanks in advance.

**Comment by Tapac** [comment] 2021-01-22 19:44
Hello, @dancing-koala ,
That looks strange as there are tests that create multiple entities in a single transaction ([EntityTest.testDefaults02()](https://github.com/JetBrains/Exposed/blob/e46038a7aa228f5af8c09be907d24a06fadaffd2/exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/entities/EntityTests.kt#L105) for example).
Can you provide a reproducible code sample?

**Comment by dancing-koala** [comment] 2021-01-25 10:50
Hi @Tapac, here is a code sample:

```kotlin

package fr.dancing_koala.sandbox

import org.jetbrains.exposed.dao.UUIDEntity
import org.jetbrains.exposed.dao.UUIDEntityClass
import org.jetbrains.exposed.dao.id.EntityID
import org.jetbrains.exposed.dao.id.UUIDTable
import org.jetbrains.exposed.sql.*
import org.jetbrains.exposed.sql.`java-time`.datetime
import org.jetbrains.exposed.sql.transactions.transaction
import java.time.LocalDateTime
import java.util.*


private val tables = arrayOf(Accounts)

fun main() {
    val now = LocalDateTime.now()
    val activeAccount = Account(UUID.randomUUID(), "account1@test.org", "Account 1", "account1pwd", now, now)
    val disabledAccount = Account(UUID.randomUUID(), "account2@test.org", "Account 2", "account2pwd", now, now, now)

    TestingDatabaseSources.connectTestingSQLite(tables)

    //--- Not working
    TestingDatabaseSources.initialize {
        activeAccount.insertInDb()
        disabledAccount.insertInDb()
    }
    //---

    //--- Working
    TestingDatabaseSources.initialize {
        activeAccount.insertInDb()
    }
    transaction {
        disabledAccount.insertInDb()
    }
    //--

    TestingDatabaseSources.clear()
}

object Accounts : UUIDTable() {
    val identity = varchar("identity", 256).uniqueIndex()
    val name = varchar("name", 256)
    val hashedPassword = varchar("hashedPassword", 256)
    val created = datetime("created")
    val updated = datetime("updated")
    val disabled = datetime("disabled").nullable().default(null)
}

class AccountEntity(id: EntityID<UUID>) : UUIDEntity(id) {
    companion object : UUIDEntityClass<AccountEntity>(Accounts)

    var identity by Accounts.identity
    var name by Accounts.name
    var hashedPassword by Accounts.hashedPassword
    var created by Accounts.created
    var updated by Accounts.updated
    var disabled by Accounts.disabled
}

data class Account(
    val id: UUID,
    val identity: String,
    val name: String,
    val hashedPassword: String,
    val created: LocalDateTime,
    val updated: LocalDateTime,
    val disabled: LocalDateTime? = null
)

fun Account.insertInDb() = AccountEntity.new(this@insertInDb.id) {
    identity = this@insertInDb.identity
    name = this@insertInDb.name
    hashedPassword = this@insertInDb.hashedPassword
    created = this@insertInDb.created
    updated = this@insertInDb.updated
    disabled = this@insertInDb.disabled
}

object TestingDatabaseSources {

    private lateinit var db: Database
    private var tables: Array<out Table> = emptyArray()

    fun connectTestingSQLite(tables: Array<out Table>) {
        db = Database.connect("jdbc:sqlite:assets/test.db", "org.sqlite.JDBC")
        TestingDatabaseSources.tables = tables
    }

    fun initialize(logQueries: Boolean = false, initBlock: () -> Unit) {
        transaction {
            SchemaUtils.create(*tables)
            initBlock()
        }
    }

    fun clear() {
        transaction {
            tables.forEach { it.deleteAll() }
        }
    }
}

```

_Notes_: 
* I tried to run it as a project in itself (eg: using a simple kotlin project with a **main()** function), it the exception still happens
* You shoud comment either the "working" or the "not working" block before running.

**Comment by Tapac** [comment] 2021-04-14 19:33
Can you please check your code with Exposed 0.30.1 as I've got another (expected) exception near "//Working" part:
`[SQLITE_CONSTRAINT_UNIQUE]  A UNIQUE constraint failed (UNIQUE constraint failed: Accounts.identity)`

**Comment by dancing-koala** [comment] 2021-05-20 15:54
Hi Tapac, I confirm that I don't have the crash anymore with **0.31.1** . The "UNIQUE constraint" one you got is due to the **clear()** function being wrong, not a bug of Exposed.

Sorry for the late feedback and thank you for everything.

Have a nice day.

**Comment by joc-a** [comment] 2023-05-09 14:43
Hello @dancing-koala. It looks like this is resolved, so I will close this issue. If there are any further issues, please report them on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED). Thanks.

**Closed by joc-a** 2023-05-09 14:43 UTC
