### ISSUE TITLE
Ability to specify comments for columns in table

### ISSUE THREAD

**Issue by FRedEnergy** [JetBrains/Exposed#802] opened 2020-02-19 21:43 UTC
I wasn't able to find any information about how we can provide comments for table columns. It can be essential when SchemaUtils.createMissingTablesAndColumns is used for creating systems which 
 able to spin up the environment without manually creating all tables and databases. 

Right now users either have to manually create tables with initial comments, add them later after tables have been created by Exposed or completely abandon the idea of human readable descriptions for columns. 

Usage can look similiar to this example:

```kotlin
object SampleTable: Table("whatever"){
     val column = varchar("data", 32).comment("Sample column")
}
```

As far as I know all supported SQL databases allow some sort of comments/description for columns and they can be altered on already existing tables.

**Comment by Tapac** [comment] 2020-03-21 20:41
Duplicate of #58

**Closed** 2020-03-21 22:02 UTC
Labels: enhancement
