### ISSUE TITLE
java.lang.NoSuchMethodError: 'long kotlin.time.TimeSource$Monotonic.markNow-z9LOYto()'

### ISSUE THREAD

**Issue by lifestreamy** [JetBrains/Exposed#1600] opened 2022-09-26 20:49 UTC
```
Exception in thread "main" java.lang.NoSuchMethodError: 'long kotlin.time.TimeSource$Monotonic.markNow-z9LOYto()'
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:233)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:128)
	at org.jetbrains.exposed.sql.statements.Statement.execute(Statement.kt:28)
	at org.jetbrains.exposed.sql.QueriesKt.insert(Queries.kt:73)
	at DataBaseConnectivity.DataBaseConnectivity$Companion$main$insertedNamesId$1.invoke(DataBaseConnectivity.kt:25)
	at DataBaseConnectivity.DataBaseConnectivity$Companion$main$insertedNamesId$1.invoke(DataBaseConnectivity.kt:24)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:189)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:215)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:223)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:214)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:165)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:223)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:135)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:132)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:131)
	at DataBaseConnectivity.DataBaseConnectivity$Companion.main(DataBaseConnectivity.kt:24)
	at DataBaseConnectivity.DataBaseConnectivity.main(DataBaseConnectivity.kt)
```

Build.gradle : 

```
plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.7.10'
}
group = 'org.example'
version = '1.0-SNAPSHOT'


allprojects {
    repositories {
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}

dependencies {
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
    testImplementation 'org.slf4j:slf4j-api:2.0.2'
    implementation 'org.slf4j:slf4j-log4j12:1.7.29'
    implementation 'com.github.kotlin-telegram-bot.kotlin-telegram-bot:dispatcher:6.0.7'
    implementation 'org.jetbrains.exposed:exposed-core:0.39.2'
    implementation 'org.jetbrains.exposed:exposed-dao:0.39.2'
    implementation 'org.jetbrains.exposed:exposed-jdbc:0.39.2'
    implementation 'org.postgresql:postgresql:42.2.2'
}

test {
    useJUnitPlatform()
}

compileKotlin {
    kotlinOptions.jvmTarget = '16'
}

compileTestKotlin {
    kotlinOptions.jvmTarget = '16'
}
```
When setting JVM target to 1.6:

```
e: JVM target 1.6 is no longer supported. Please migrate to JVM target 1.8 or above

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

```
And with 1.8 and above I get the same error with markNow()

**Comment by lifestreamy** [comment] 2022-09-26 21:06
Everything is working correctly without errors with Exposed version 38.2

**Comment by Tapac** [comment] 2022-09-27 09:05
Duplicate of #1556. Fix will be available on a week

**Closed by Tapac** 2022-09-27 09:05 UTC
