### ISSUE TITLE
R2DBC bindings

### ISSUE THREAD

**Issue by dazraf** [JetBrains/Exposed#572] opened 2019-06-01 20:04 UTC
The drive for better throughout for I/O bound services has meant development of async database driver frameworks. One is R2DBC. This issue is to encourage debate, design, and prioritisation of work on respective bindings in Exposed. Thanks.

**Comment by Tapac** [comment] 2019-06-02 18:58
Duplicate of #456

**Closed** 2021-09-18 00:25 UTC
