### ISSUE TITLE
Spring ComponentScan could not find the Table

### ISSUE THREAD

**Issue by ChienliWang** [JetBrains/Exposed#901] opened 2020-04-30 16:07 UTC
In my spring project
Applicaiton in "com.a.b"
Tales in "com.a.c" (Of course, I used ComponentScan)
But the Exposed only scans for the "com.a.b"
I know, I can put the Application into the "com.a"
But sometime we can't do that.

**Comment by bog-walk** [comment] 2023-09-30 02:20
`exposed-spring-boot-starter` has undergone some changes and most recently `SpringTransactionManager` got an overhaul in current Exposed version 0.44.0. I'm unable to reproduce this issue using this latest version.

Using the `exposed-spring` [sample project](https://github.com/JetBrains/Exposed/tree/main/samples/exposed-spring) as an example:

If the `SpringApplication` [file](https://github.com/JetBrains/Exposed/blob/main/samples/exposed-spring/src/main/kotlin/SpringApplication.kt) is moved from its current location ("com.a") and placed into a new package `app` ("com.a.b"), the app won't initially work.
This is resolved by providing an array of the component package names as an argument for [scanBasePackages()](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/SpringBootApplication.html#scanBasePackages()), allowing the app to work -> `@SpringBootApplication(scanBasePackages = [ ])`

If there are any further issues, please consider reporting them on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763).

**Closed by bog-walk** 2023-09-30 02:20 UTC
