### ISSUE TITLE
Not being able to create a FK for a table created in another database schema

### ISSUE THREAD

**Issue by PedroStrabeli** [JetBrains/Exposed#701] opened 2019-11-27 12:21 UTC
So I'm trying to create table for authentication on my `postgresql` db.

This table should be in a dedicated schema in my database, called, let's say: `authentication`, to be simple. All's good, I can define and create the table by using:

```
object UserTable: Table("authentication.user") {
  val id = integer("id").primaryKey().autoIncrement()
  val name = varchar("name", 200)
  val type = integer("type").references(UserTypeTable().id)
}
```
The creation of the table is ok on a different schema without the `FK`, but when it defines the `FK`,  it fails, because it uses the name of the table as suffix for the FK's name.

So it's something like `fk_authentication.user_fk_type_id`, which is a no go, since there cannot be a `.` on the fk's name and I get a syntax error.

```
[main] WARN Exposed - Transaction attempt #0 failed: org.postgresql.util.PSQLException: ERROR: syntax error at or near "."
  Statement(s): CREATE TABLE IF NOT EXISTS authentication.user (id INT PRIMARY KEY, "name" VARCHAR(200) NOT NULL, type INT NOT NULL CONSTRAINT fk_authentication.user_fk_type_id FOREIGN KEY (type) REFERENCES authentication.user_type(id) ON DELETE RESTRICT ON UPDATE RESTRICT)
org.jetbrains.exposed.exceptions.ExposedSQLException: org.postgresql.util.PSQLException: ERROR: syntax error at or near "."
```

> note: I changed the statement to be relatable to the query I wrot:e here as an example. Do not attain to the statement, but to the problem at hand, to correct the syntax.

So I think of 2 possibilities:

 - Define table schema in another way, somehow?
 - Define FK name explicitely.

Can I do any of those? or should I approach this in another way? 
I'm trying to do both by looking at the `Table.kt` code, but not finding anything that I can use... Is there a workaround?

Thank you

**Comment by Tapac** [comment] 2019-11-29 21:42
Duplicate of #145

**Comment by PedroStrabeli** [comment] 2019-11-30 03:57
Sorry, but I beg to differ. This is not a duplicate. 
#145 goes on about creating table and joining cross-schema. I was able to create the table in a different schema, as stated on my question, but the issue here is **creating a Foreign Key on that table, in another schema**. 
As stated, the **automatic naming of the Foreign Key is the problem**. The automatic naming uses fk_**[name_of_table]**_fk_[field1]_[field2].

And the issue is: If the name of the table was set with a schema on it, the name of the fk gets a dot (.) on it, which invariably fails the syntax. A FK name cannot contain a dot.

This is the problem.
The solution I'm looking for is either:

1. Name the FK myself 
2. Set the schema differently for the table (Which from #145 I believe is not possible. 

Thank you

**Comment by Tapac** [comment] 2019-12-29 16:16
Should be already released

**Closed by Tapac** 2019-12-29 16:16 UTC

**Comment by PedroStrabeli** [comment] 2019-12-30 14:26
Great, thanks.
