### ISSUE TITLE
DAO inner objects cause closed ResultSet error

### ISSUE THREAD

**Issue by berkus** [JetBrains/Exposed#56] opened 2016-10-16 09:59 UTC
Scenario:
```
            val objs = PlannedActivity.all().forEach { act ->
                activs.append("<b>"+act.id+"</b>: "+
                    act.members.joinToString { memb -> memb.user.psnName + " (@" + memb.user.telegramName + ")" }+
                    " going to " + act.activity.name + " " + act.activity.mode +
                    " at <b>" + formatStartTime(act.start) + "</b>\n")
            }
```

`members` and `activity` are external fields causing another query:

```
object PlannedActivities : IntIdTable() {
    val authorId = reference("author_id", Users)
    val activityId = reference("activity_id", Activities)
}

class PlannedActivity(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<PlannedActivity>(PlannedActivities)

    var author by User referencedOn PlannedActivities.authorId
    var activity by Activity referencedOn PlannedActivities.activityId

    val members by PlannedActivityMember referrersOn PlannedActivityMembers.plannedActivityId
}

object PlannedActivityMembers : IntIdTable() {
    val plannedActivityId = reference("planned_activity_id", PlannedActivities)
    val userId = reference("user_id", Users)

    init {
        index(true, plannedActivityId, userId)
    }
}
```

SQL queries:
```
SQL: SELECT PlannedActivities.id, PlannedActivities.author_id, PlannedActivities.activity_id, PlannedActivities.details, PlannedActivities."start" FROM PlannedActivities
SQL: SELECT PlannedActivityMembers.id, PlannedActivityMembers.planned_activity_id, PlannedActivityMembers.user_id, PlannedActivityMembers.added FROM PlannedActivityMembers WHERE PlannedActivityMembers.planned_activity_id = 1
SQL: SELECT Users.id, Users.telegram_name, Users.telegram_id, Users.psn_name, Users.email, Users.psn_clan, Users.created_at, Users.updated_at, Users.deleted_at, Users.tokens, Users.pending_activation_code FROM Users WHERE Users.id = 2
```

The above query causes error with pgsql jdbc driver:
```
org.postgresql.util.PSQLException: This ResultSet is closed.
        at org.postgresql.jdbc.PgResultSet.checkClosed(PgResultSet.java:2740)
        at org.postgresql.jdbc.PgResultSet.next(PgResultSet.java:1817)
        at org.jetbrains.exposed.sql.Query$ResultIterator.hasNext(Query.kt:211)
        at org.jetbrains.exposed.sql.IterableExKt$mapLazy$1$iterator$1.hasNext(IterableEx.kt:107)
        at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:1922)
        at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:1943)
        at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:1942)
        at org.aeriagloris.telegram.commands.ListCommand$execute$1.invoke(ListCommand.kt:24)
        at org.aeriagloris.telegram.commands.ListCommand$execute$1.invoke(ListCommand.kt:14)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:69)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:57)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:48)
```

Any advice on a workaround?

**Comment by Tapac** [comment] 2016-10-17 08:43
The problem is that all() function (a long with find{}) returns SizedCollection which is wrapper over jdbc ResultSet. On each .next() invocation it returns next row from result set and wrap it with resulting Entity. 
Purpose of this is to allow client not too fetch overall data on all(), but only while it needed.

As PSQL doesn't support concurrent requests within same connection, first result set (`Select * FROM PlannedActivities query`) is closing by driver and you fail with `org.postgresql.util.PSQLException: This ResultSet is closed` exception.

Workaround is to load everything before .forEach() with simple .toList():
`  val objs = PlannedActivity.all().toList().forEach { act ->
                activs.append("<b>"+act.id+"</b>: "+
                    act.members.joinToString { memb -> memb.user.psnName + " (@" + memb.user.telegramName + ")" }+
                    " going to " + act.activity.name + " " + act.activity.mode +
                    " at <b>" + formatStartTime(act.start) + "</b>\n")
            }`

**Comment by berkus** [comment] 2016-10-18 18:23
It worked! Thank you.

Definitely deserves a line in the docs.

**Closed** 2016-10-20 07:45 UTC
Labels: documentation
