### ISSUE TITLE
Operator `eq` inside `deleteWhere` cannot be resolved

### ISSUE THREAD

**Issue by schubmat** [JetBrains/Exposed#1698] opened 2023-03-06 19:09 UTC
When using the operator `eq` inside `deleteWhere` everything works fine up to release `39.2`. Since I recently came across `40.1` and `41.1` respectively I got compile errors. The change log states that there have been changes to `deleteWhere` with `40.1`. Therefore, that might be the source of the issue?! 

Sample:

```kotlin
fun delete(id: UUID) = transaction {
        TableObject.deleteWhere { TableObject.id eq id }
    }
```

works just fine with `39.2`. 

With the latest releases I just get the following error message:

```bash
file:///home/XXX/src/main/kotlin/de/XXX...XXX.kt:70:70 Unresolved reference: eq
```

Only the usage of `eq` inside `deleteWhere` is affected. All other usages do not cause any trouble.

**Comment by PoisonedYouth** [comment] 2023-03-10 19:53
Can you please check if adding
`import org.jetbrains.exposed.sql.SqlExpressionBuilder.eq`
import solves the problem?

**Comment by PoisonedYouth** [comment] 2023-03-16 16:24
Which Exposed dependencies you are using? I'm not able to reproduce this with my configuration.

**Comment by lns-ross** [comment] 2023-03-16 17:15
You may need to reference this one instead:
`org.jetbrains.exposed.sql.ISqlExpressionBuilder#eq`

Note the 'I'

This is the one that works for me.

**Comment by PoisonedYouth** [comment] 2023-03-16 18:12
I checked your code again with `39.2` -> the import is not necessary. After updating to `0.41.1` the import is necessary and can be imported as extension function with the import I already posted. Sorry I did not find any potential problem...

**Comment by alexmaryin** [comment] 2023-04-04 07:53
I faced the same problem in Exposed version 0.41.1. Mentioned import helps to build the project, but this import marked as unused in Idea and may be deleted if import optimization called.

**Comment by AlexeySoshin** [comment] 2023-04-08 19:39
This is most probably related to #1561 , but @PoisonedYouth comment is correct and `import org.jetbrains.exposed.sql.SqlExpressionBuilder.eq` should have resolved the issue.

@schubmat , what happens if you rewrite the query as follows:

```kotlin
fun delete(id: UUID) = transaction {
        TableObject.deleteWhere { this.id eq id }
    }
```

Does it make any difference?

**Comment by wlara** [comment] 2023-04-10 17:12
Seeing the same issue with 0.41.0. Manually import doesn't help.

**Comment by timmc** [comment] 2023-04-16 21:43
See https://github.com/JetBrains/Exposed/issues/1610 for an earlier discussion.

**Closed** 2023-06-01 09:59 UTC

**Comment by bog-walk** [comment] 2023-06-01 10:04
Please consider reopening this issue on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763) if the problem persists despite the proposed changes in [the revised changelog](https://github.com/JetBrains/Exposed/blob/master/docs/ChangeLog.md#0401).
