### ISSUE TITLE
Inserting data in DateTime fields

### ISSUE THREAD

**Issue by apriyans-blk** [JetBrains/Exposed#679] opened 2019-11-06 04:19 UTC
I have a model with the "created_at" attribute and i'm having trouble saving data into it. It is always expecting a DateTime object. I researched around a bit to find that it is provided by the Joda DateTime library. Joda is not currently being actively supported and they have suggested to used the time library of Java8.

My question is how exactly are we saving timestamps to DATETIME filed in a postgres database using Kotlin exposed.

**Comment by Tapac** [comment] 2019-11-15 16:36
Duplicate of #100

**Comment by Tapac** [comment] 2019-11-15 16:37
Java 8 Time API is comming soon.

**Comment by Tapac** [comment] 2019-11-16 17:36
Released in 0.18.1
https://github.com/JetBrains/Exposed/wiki/LibDocumentation#exposed-0181-and-higher

**Closed by Tapac** 2019-11-16 17:36 UTC
