### ISSUE TITLE
DAO on compound/multiple primary key ? 

### ISSUE THREAD

**Issue by scorsi** [JetBrains/Exposed#964] opened 2020-06-17 20:20 UTC
Hello,

PostgreSQL can use multiple fields as Primary Key ([doc](https://www.postgresql.org/docs/current/ddl-constraints.html#DDL-CONSTRAINTS-PRIMARY-KEYS)) but how to handle that with Exposed DAO ?

I tried to use the DAO with a table which is quite complexe. Because example is better than words. Here the SQL :
```sql
CREATE TABLE table__contacts_first
(
    contact_id    UUID         NOT NULL,
    app_id        VARCHAR(128) NOT NULL,

    --- other fields ...

    FOREIGN KEY (contact_id) REFERENCES table__contacts (contact_id),
    PRIMARY KEY (contact_id, app_id)
);
```
As you can see, the `table__contacts_first` doesn't have any PK, but the pair `contact_id` + `app_id` acts as is.
I have the following Exposed Table:
```kotlin
object ContactsFirstTable : Table(name = "table__contacts_first") {
    val contactId = reference("contact_id", ContactsTable).primaryKey()
    val appId = varchar("app_id", length = 128).primaryKey()
}
```
And now the Exposed DAO:
```kotlin
class ContactFirstDao(id: EntityID<UUID>) : UUIDEntity(id) {
    companion object : UUIDEntityClass<ContactFirstDao>(ContactsFirstTable)
}
```
Obviously, I got errors and in fact, I should construct my `ContactFirstDao` using `contactId` and `appId`.

Do you have any idea how I could achieve that ?

Thanks 👍

**Comment by michaelbrylevskii** [comment] 2020-07-02 16:47
Hi, maybe I didn’t understand it, but according to this guide we can specify two primary keys in the table definition and bind table fields to entity fields.
Section "8.8. Many-to-Many Associations" https://www.baeldung.com/kotlin-exposed-persistence

**Comment by scorsi** [comment] 2020-07-02 20:41
Hello @michaelbrylevskii thanks for the answer but it didn't answer to my question at all.

It is not a "many-to-many" associations but just a foreign key on a compound primary keys.

I have a table with two primary key, how could I do that:
```kotlin
class MyDao(primaryKeyOne: EntityID<UUID>, primaryKeyTwo: EntityID<UUID>) : UUIDEntity(primaryKeyOne, primaryKeyTwo) {
    companion object : UUIDEntityClass<MyDao>(MyTable)
}
class MyDao(primaryKey EntityID<UUID, UUID>) : UUIDEntity(primaryKey) {
    companion object : UUIDEntityClass<MyDao>(MyTable)
}
class MyDao(primaryKey EntityID<Pair<UUID, UUID>>) : UUIDEntity(primaryKey) {
    companion object : UUIDEntityClass<MyDao>(MyTable)
}
```
All of thoses don't work. It is missing in the library.

Do you understand now ?

**Comment by JulianBissekkou** [comment] 2020-09-10 14:05
Is there any update to this? I am looking for this feature as well

**Comment by scorsi** [comment] 2020-09-15 12:53
I left Exposed caused of that important issue. Anyone in the staff behind the lib seams to be interested into this, it's still unassigned...

**Comment by PedroD** [comment] 2020-10-15 12:22
This is something so basic at the SQL level, why is Exposed failing at addressing this? So strange.

**Comment by scorsi** [comment] 2020-10-15 13:35
Agreed, very strange.

**Comment by deweyx** [comment] 2020-11-01 19:53
Wouldn't it just be:

```kotlin
object ContactsFirstTable : Table(name = "table__contacts_first") {
    val contactId = reference("contact_id", ContactsTable).primaryKey(0)
    val appId = varchar("app_id", length = 128).primaryKey(1)
}
```

(notice the parameter to `.primaryKey(...)`)

**Comment by jnfeinstein** [comment] 2020-11-11 16:14
I naively attempted to use a `CompositeColumn` as the ID column, but was blocked by [this](https://github.com/JetBrains/Exposed/blob/master/exposed-core/src/main/kotlin/org/jetbrains/exposed/sql/Table.kt#L474).  Composite columns appear to inherit from `Expression` as opposed to `Column`.

**Comment by gringofe** [comment] 2020-11-26 13:19
> I left Exposed caused of that important issue. Anyone in the staff behind the lib seams to be interested into this, it's still unassigned...

Hi, I was just wondering what library you are using now?

**Comment by scorsi** [comment] 2020-11-26 13:28
An amaizing library: SQL ! I stopped using libraries, ORMs, ... Just SQL is enough.
But you can take a look at Ktorm (https://ktorm.liuwj.me/).

I left that issue open because it's an importante missing feature.

**Comment by PedroD** [comment] 2020-12-17 13:08
> 
> 
> An amaizing library: SQL ! I stopped using libraries, ORMs, ... Just SQL is enough.
> But you can take a look at Ktorm (https://ktorm.liuwj.me/).
> 
> I left that issue open because it's an importante missing feature.

That's been my approach since ever, but I got tired of making all CRUD methods manually for every new project. Waste of time, prone to error, and more code to maintain.

**Comment by PedroD** [comment] 2020-12-17 13:20
> 
> 
> An amaizing library: SQL ! I stopped using libraries, ORMs, ... Just SQL is enough.
> But you can take a look at Ktorm (https://ktorm.liuwj.me/).
> 
> I left that issue open because it's an importante missing feature.

If Ktorm can do this, then I'm sold: https://github.com/kotlin-orm/ktorm/issues/220

**Comment by sickfar** [comment] 2021-04-11 15:19
Hello there

Just created an extension library for that (modifying exposed-dao part). Hope it will help you
https://gitlab.com/sickfar/exposed-dao-composite

**Comment by szakerx** [comment] 2021-11-04 10:47
So it's almost a year and still nothing? :(

**Comment by rodrigogs** [comment] 2021-11-04 20:25
> So it's almost a year and still nothing? :(

I ended up going with [ktorm](https://www.ktorm.org/).

It's pretty good, but I have to be honest...

I, more than anybody, aim to avoid using Spring and hibernate for everything, just because I don't believe that almost an entire community should rely basically on a single toolset. The problem is: Kotlin libraries are amazing, but most of them are not mature like good old Java libs that ppl have been using for decades now.
I'm also facing problems with ktorm, it's not all roses.

My suggestions are:
- if you are developing something critical, go for hibernate or something like it
- if you are toying around with code or developing some PoC, you might like to struggle a little bit with ktorm
- Exposed is not an option since it does not have basic mapping features like composite keys

**Comment by alexanderbsingh** [comment] 2023-01-19 21:16
I know this issue is old now but this seems to been solved. 

```
object myTable : Table() {
    val column1 = varchar("column1", 256)
    val column2 = varchar("column2", 256)

    override val primaryKey = PrimaryKey(arrayOf(column1, column2), "compositeKey")
}
```

**Comment by szakerx** [comment] 2023-01-19 21:45
> I know this issue is old now but this seems to been solved.
> 
> ```
> object myTable : Table() {
>     val column1 = varchar("column1", 256)
>     val column2 = varchar("column2", 256)
> 
>     override val primaryKey = PrimaryKey(arrayOf(column1, column2), "compositeKey")
> }
> ```

Sir, we are talking about dao, not sql dsl

**Comment by rafaz182** [comment] 2023-03-03 11:17
I just reached this point today. I'll try figure out how to bypass it.

**Comment by rChaoz** [comment] 2023-04-14 20:06
Any luck with that? @rafaz182

**Comment by BierDav** [comment] 2023-05-11 11:42
Are there any updates on this topic?

**Comment by VitSun666** [comment] 2023-06-07 14:18
Same issue here

**Comment by mairs8** [comment] 2023-07-21 18:07
any updates?

**Comment by fengelniederhammer** [comment] 2023-09-25 11:30
We also need this feature. Are you planning do implement it?

**Comment by sundaycrafts** [comment] 2024-02-19 12:34
I think it has been archived. You can pass multiple values as a primary key like below:

```kotlin
import org.jetbrains.exposed.sql.*

data class Article(val title: String, val body: String)

object Articles : Table() {
    val title = varchar("title", 128)
    val body = varchar("body", 1024)

    override val primaryKey = PrimaryKey(title, body)
}
```

The result:

![image](https://github.com/JetBrains/Exposed/assets/4732821/abdc0b3b-2bd9-4656-9229-f7559bf16add)


You can check the rest of the code to make sure the work by following the official short tutorial:
https://ktor.io/docs/interactive-website-add-persistence.html

**Comment by BierDav** [comment] 2024-02-19 13:56
The reason to use dao is to not have to write this boilerplate code, of course it is possible to implement a dao like thing with dsl, but it will introduce a lot of disgusting code duplication

**Comment by sundaycrafts** [comment] 2024-02-20 10:50
Thank you. I don't intend to argue against your opinion, but my primary personal reason for using DAO is to code type-safe applications, not to remove boilerplate. However, I completely agree that the DAOFacade implementation appears redundant upon first impression. I haven't considered DAO carefully, though.

(To be honest, in the first place, I lack a clear picture of how resolving this issue would eliminate the need for boilerplate)

**Closed** 2024-07-18 19:35 UTC
