### ISSUE TITLE
ThreadLocalTransactionManager issues with executors

### ISSUE THREAD

**Issue by SahilLone** [JetBrains/Exposed#553] opened 2019-04-28 20:09 UTC
The default behaviour of `Database.connect` is to use `ThreadLocalTransactionManager` which uses thread local to store the currenct transactions.
I think the design is like this to make it possible to bind single transaction for nested transaction calls spanning across functions.

The problem with it is when I start using some schedulers and execution services , the binding of transactions to the Thread local is a dangerous behaviour.
This makes is it a companion of what Spring framework is doing.
Since kotlin has a better support for functional programming, I think there could have been a better ways to solve this.

I would expect the user to start the transaction itself and pass on the transation context to the functions to wrap the execution. 
Look at the simple below example
```
transaction {
    for (
        i <- someFunctionReturningFutureOfResultFromDatabase()
        j <-  otherFunctionReturningFutureOfResultFromDatabase()
   yield (i, j)

}
```

The above program fails miserably as it leaves the database incosistent.
The same result is expected if we use any form of async commputation constructs.
The library is not easy to use in any reactive frameworks where context switching is at the core

**Comment by Tapac** [comment] 2019-06-02 19:03
Duplicate of #255

**Closed** 2019-10-12 17:33 UTC
