### ISSUE TITLE
Can't load implementation for DatabaseConnectionAutoRegistration

### ISSUE THREAD

**Issue by XjCyan1de** [JetBrains/Exposed#748] opened 2019-12-30 16:17 UTC
```
java.lang.ExceptionInInitializerError: null
	at one.xjcyan1de.creativeplus.CreativePlus.connectDatabase(CreativePlus.kt:70) ~[?:?]
	at one.xjcyan1de.creativeplus.CreativePlus.enable(CreativePlus.kt:43) ~[?:?]
	at com.github.xjcyan1de.cyanlibz.plugin.ExtendedBukkitPlugin.onEnable(ExtendedBukkitPlugin.kt:38) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.1.jar:git-Paper-27]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.15.1.jar:git-Paper-27]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.15.1.jar:git-Paper-27]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[patched_1.15.1.jar:git-Paper-27]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.1.jar:git-Paper-27]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481) ~[patched_1.15.1.jar:git-Paper-27]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.15.1.jar:git-Paper-27]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.1.jar:git-Paper-27]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalStateException: Can't load implementation for DatabaseConnectionAutoRegistration
	at org.jetbrains.exposed.sql.Database.<clinit>(Database.kt:64) ~[?:?]
	... 12 more
```

CreativePlus.connectDatabase:
```
    private fun connectDatabase() = Database.connect(
        HikariDataSource(HikariConfig().apply {
            jdbcUrl = Config.sqlUrl
            driverClassName = Config.sqlDriver
            username = Config.sqlUsername
            password = Config.sqlPassword
            maximumPoolSize = 4
            addDataSourceProperty("cachePrepStmts", "true")
            addDataSourceProperty("prepStmtCacheSize", "250")
            addDataSourceProperty("prepStmtCacheSqlLimit", "2048")
            addDataSourceProperty("characterEncoding", "utf8")
            addDataSourceProperty("useUnicode", "true")
            addDataSourceProperty("useSSL", "false")
            addDataSourceProperty("useJDBCCompliantTimezoneShift", "true")
            addDataSourceProperty("useLegacyDatetimeCode", "false")
            addDataSourceProperty("serverTimezone", TimeZone.getDefault().id)
        })
    )
```

**Comment by XjCyan1de** [comment] 2019-12-30 16:18
System Info: Java 11 (Dynamic Code Evolution 64-Bit Server VM 11.0.5+5-201912121506) Host:  Windows 10 10.0 (amd64)

**Comment by XjCyan1de** [comment] 2019-12-30 16:20
kotlin-stdlib-1.3.61
exposed-core-0.20.2

**Comment by StepByStepler** [comment] 2019-12-30 18:23
Encountered the same issue. The problem is that exposed classes here are loaded by other ClassLoader instance, but line 64 of org.jetbrains.exposed.sql.Database uses contextClassLoader under the hood: `ServiceLoader.load(DatabaseConnectionAutoRegistration::class.java)` invokes overload with `Thread.currentThread().getContextClassLoader()`. I suggest to manually specify the classloader to search (`org.jetbrains.exposed.sql.Database::class.java.classLoader`, for example). This way dynamically loaded jars (like Bukkit plugins) can also use Exposed.

**Comment by Tapac** [comment] 2019-12-30 22:01
You have to add `exposed-jdbc` into your dependency. It's a transport layer implementation (the only at the moment).

**Comment by XjCyan1de** [comment] 2019-12-31 00:57
@Tapac its already added. but ServiceLoader didn't load DatabaseConnectionAutoRegistration as service, because Bukkit classloader. Check @StepByStepler comment

**Comment by XjCyan1de** [comment] 2019-12-31 01:38
So if i use @StepByStepler suggestion its loads exposed-jdbc connection impl. but exposed still use context service loader.

```
        val bukkitClassLoader = Database::class.java.classLoader
        val bukkitServiceLoader = ServiceLoader.load(DatabaseConnectionAutoRegistration::class.java,bukkitClassLoader)
        println("[Bukkit] ClassLoader: $bukkitClassLoader ServiceLoader: ${bukkitServiceLoader.toList()}")

        val contextClassLoader = Thread.currentThread().contextClassLoader
        val contextServiceLoader = ServiceLoader.load(DatabaseConnectionAutoRegistration::class.java,contextClassLoader)
        println("[Context] ClassLoader: $contextClassLoader ServiceLoader: ${contextServiceLoader.toList()}")

        database = connectDatabase()
```
```
[04:36:11 INFO]: [Bukkit] ClassLoader: org.bukkit.plugin.java.PluginClassLoader@3688059d ServiceLoader: [org.jetbrains.exposed.jdbc.ExposedConnectionImpl@dd5cd47]
[04:36:11 INFO]: [Context] ClassLoader: jdk.internal.loader.ClassLoaders$AppClassLoader@e73f9ac ServiceLoader: []
[04:36:11 ERROR]: Error occurred while enabling CreativePlus v1.0-SNAPSHOT (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at one.xjcyan1de.creativeplus.CreativePlus.connectDatabase(CreativePlus.kt:80) ~[?:?]
	at one.xjcyan1de.creativeplus.CreativePlus.enable(CreativePlus.kt:53) ~[?:?]
	at com.github.xjcyan1de.cyanlibz.plugin.ExtendedBukkitPlugin.onEnable(ExtendedBukkitPlugin.kt:43) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.1.jar:git-Paper-27]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.15.1.jar:git-Paper-27]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.15.1.jar:git-Paper-27]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[patched_1.15.1.jar:git-Paper-27]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.1.jar:git-Paper-27]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481) ~[patched_1.15.1.jar:git-Paper-27]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.15.1.jar:git-Paper-27]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.1.jar:git-Paper-27]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalStateException: Can't load implementation for DatabaseConnectionAutoRegistration
	at org.jetbrains.exposed.sql.Database.<clinit>(Database.kt:64) ~[?:?]
	... 12 more
```

**Comment by Tapac** [comment] 2020-01-03 20:26
Fixed in master. Will be released soon.

**Closed by Tapac** 2020-01-03 20:26 UTC
Labels: bug

**Comment by du-it** [comment] 2020-12-17 13:02
It's still in version 0.28.1

**Comment by vladfrangu** [comment] 2021-01-10 17:01
This issue also seems to occur with relocating via shadow jars... 👀 Any idea what can be done to solve this?

**Comment by dtbullock** [comment] 2021-01-21 11:19
> It's still in version 0.28.1

I'm on 0.28.1, and the advice to include exposed-jdbc worked for me.

**Comment by SecretX33** [comment] 2021-09-24 13:05
I had this issue too, in my case I was excluding all files inside `META-INF` from being shaded, by removing that exclude I got rid of this issue ([credits](https://github.com/JetBrains/Exposed/issues/792#issuecomment-588479799)).

**Comment by SecretX33** [comment] 2021-09-26 23:59
> 
> 
> This issue also seems to occur with relocating via shadow jars... 👀 Any idea what can be done to solve this?

I'm getting this issue after relocating this dependency via shadow jar too, and I have no idea how to fix that.

**Comment by WillFP** [comment] 2022-04-06 12:31
Still having this issue?

**Comment by Tapac** [comment] 2022-04-09 11:27
@WillFP , did you add `exposed-jdbc` as a dependency? Do you use package relocation?

**Comment by maciejtulaza** [comment] 2022-06-01 06:45
in my case changing `runtimeOnly("org.jetbrains.exposed:exposed-jdbc:0.38.2")` into `implementation("org.jetbrains.exposed:exposed-jdbc:0.38.2")` helped

**Comment by nathanfallet** [comment] 2023-11-19 16:05
I spent some time on this issue because it was happening to me as well:
I was excluding `META-INF/**` from fat jar to avoid duplicates errors when creating the jar file, so I was excluding service loading metadata as well.
So if anyone still have this problem, check that `META-INF/services/org.jetbrains.exposed.sql.DatabaseConnectionAutoRegistration` is in your jar file (else, review your exclusion patterns or use `duplicatesStrategy = DuplicatesStrategy.EXCLUDE` to exclude duplicates)

**Comment by 1fexd** [comment] 2024-05-09 12:56
> I spent some time on this issue because it was happening to me as well: I was excluding `META-INF/**` from fat jar to avoid duplicates errors when creating the jar file, so I was excluding service loading metadata as well. So if anyone still have this problem, check that `META-INF/services/org.jetbrains.exposed.sql.DatabaseConnectionAutoRegistration` is in your jar file (else, review your exclusion patterns or use `duplicatesStrategy = DuplicatesStrategy.EXCLUDE` to exclude duplicates)

Thanks!
