### ISSUE TITLE
Parameter index out of range when using Table.replace

### ISSUE THREAD

**Issue by fhntv24** [JetBrains/Exposed#98] opened 2017-02-26 15:48 UTC
When you are doing replace statement, and not all of fields is filled ( that are default ), you get this exception:
```
Caused by: java.sql.SQLException: Parameter index out of range (3 > number of parameters, which is 2).
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:545)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:505)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:479)
        at com.mysql.cj.jdbc.PreparedStatement.checkBounds(PreparedStatement.java:3246)
        at com.mysql.cj.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3230)
        at com.mysql.cj.jdbc.PreparedStatement.setInternal(PreparedStatement.java:3263)
        at com.mysql.cj.jdbc.PreparedStatement.setLong(PreparedStatement.java:3280)
        at com.mysql.cj.jdbc.PreparedStatement.setObject(PreparedStatement.java:3472)
        at org.jetbrains.exposed.sql.ColumnType.setParameter(ColumnType.kt:58)
        at org.jetbrains.exposed.sql.statements.StatementKt.fillParameters(Statement.kt:110)
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_main(Statement.kt:45)
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:105)
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:99)
        at org.jetbrains.exposed.sql.statements.Statement.execute(Statement.kt:22)
        at org.jetbrains.exposed.sql.QueriesKt.replace(Queries.kt:61)
```

Example code to reproduce:
```
object NewAuth : Table() {
    val username = varchar("username", 16).primaryKey()
    val session = binary("session", 64)
    val timestamp = long("timestamp").default(0)
    val serverID = varchar("serverID", 64).default("")
}

NewAuth.replace {
    it[username] = `object`.username
    it[session] = currentSession
}
```

But this works ( same table ):
```
NewAuth.replace {
    it[username] = `object`.username
    it[session] = currentSession
    it[timestamp] = 0
    it[serverID] = ""
}
```

Version: 0.7.6
Driver: 'mysql', name: 'mysql-connector-java', version: '6.0.5'

(Also, I cannot find any templates for reporting issues. I'm blind, or there is none at all?)

**Comment by Tapac** [comment] 2017-02-27 12:19
@fhntv24 , the issue caused by that Exposed is not support inserts with all default values. 
Will be fixed soon, thank you for reporting.

**Closed** 2017-04-10 12:38 UTC
Labels: bug
