### ISSUE TITLE
inList filtering causes error with PostgreSQL

### ISSUE THREAD

**Issue by bbodi** [JetBrains/Exposed#5] opened 2015-02-10 17:41 UTC
The following code
```kotlin
EventField.deleteWhere({ EventField.id.inList(fieldIdList) }) // fieldList is a List<Int>
```
causes the following error with PostgreSQL:
```
Can't infer the SQL type to use for an instance of java.util.ArrayList. Use setObject() with an explicit Types value to specify the type to use.
```

If I comment out the following code, it works fine.
Op.kt:74, InListOrNotInListOp.toSQL
```kotlin
DatabaseVendor.PostgreSQL -> {
    queryBuilder.registerArgument(list, expr.columnType)
}
```

**Comment by Tapac** [comment] 2016-02-24 09:38
Can you attach snippet/example to run against empty DB and reproduce that exception?
But right now it looks like a bug.

Also, please, provide postgreSQL driver and server versions. 
Thank you.

**Comment by Tapac** [comment] 2016-03-22 15:56
Closing with test in https://github.com/JetBrains/Exposed/commit/cacc1c88298d8ba2f77dcf24601f4e84e0930429

**Closed by Tapac** 2016-03-22 15:56 UTC
