### ISSUE TITLE
0.41.1 causes exception when trying to read byte column from H2

### ISSUE THREAD

**Issue by kimble** [JetBrains/Exposed#1633] opened 2022-11-17 14:02 UTC
This commit turns even really short byte arrays into streams https://github.com/JetBrains/Exposed/commit/4a97034f0abfca04092e608ad99114e938e503e1

The call to reset on the input stream breaks Exposed with H2 because the InputStream implementation used by H2 doesn't implement reset. It also seems a bit wasteful to create a stream each time. 

```
Caused by: java.io.IOException: mark/reset not supported
	at java.base/java.io.InputStream.reset(InputStream.java:733)
	at java.base/java.io.FilterInputStream.reset(FilterInputStream.java:224)
	at org.jetbrains.exposed.sql.statements.api.ExposedBlob.getBytes(ExposedBlob.kt:8)
```

**Comment by Tapac** [comment] 2022-11-17 15:32
@kimble what h2 version do you use? As there is a test on the blob field.

The idea is not to store bytes in the memory and back it with input stream.

It would help if you'll share some reproducible sample code.

**Comment by kimble** [comment] 2022-11-18 08:42
I'm using H2 version 2.1.214. 

I'll see if I'm able to make some sample code.

**Comment by axle-h** [comment] 2022-12-09 10:15
Same thing here, only workaround is to go back to 0.40.1

**Comment by Tapac** [comment] 2022-12-11 20:22
@kimble, @axle-h could you please share how you work with blob column as I can't reproduce the problem?

**Comment by axle-h** [comment] 2022-12-11 23:12
> @kimble, @axle-h could you please share how you work with blob column as I can't reproduce the problem?

H2 implements "small" & "large" BLOBs differently and this issue affects large BLOBS only. Maybe you have no coverage for large BLOBs?

I have a demo: https://github.com/axle-h/exposed-issue-1633-demo

**Comment by NiclasHaderer** [comment] 2023-02-22 14:35
I can confirm that this is happening

**Comment by joc-a** [comment] 2023-04-06 10:52
Hi @kimble. This issue should be resolved by this [commit](https://github.com/JetBrains/Exposed/commit/367babcb). I will close this issue, but please re-open it if the error is still happening.

**Closed by joc-a** 2023-04-06 10:52 UTC
