### ISSUE TITLE
A NoSuchMethodError was encountered

### ISSUE THREAD

**Issue by iPisces77** [JetBrains/Exposed#1594] opened 2022-09-13 06:25 UTC
I am using
Springboot+kotlin+Exposed to create a RBAC service, when I use Exposed query, I get the following error
![image](https://user-images.githubusercontent.com/39837211/189825706-60d65a31-6a4c-469d-ae76-4c3371441a79.png)
I have tried 0.39.2 0.39.1, the error is still there

**Comment by AlexeySoshin** [comment] 2022-09-13 08:48
Could you post your `build.gradle`/`pom.xml`, please?

My guess would be that you're missing the Kotlin DateTime library at runtime:
https://mvnrepository.com/artifact/org.jetbrains.exposed/exposed-kotlin-datetime/0.39.2

**Comment by Tapac** [comment] 2022-09-13 11:33
It will be fixed in the next release. Duplicate of #1556

**Closed by Tapac** 2022-09-13 11:33 UTC
