### ISSUE TITLE
Execute stored procedures with resultSet, MS SQL

### ISSUE THREAD

**Issue by TemichCh** [JetBrains/Exposed#1249] opened 2021-05-26 11:54 UTC
I have SQL stored procedure that returns a resultset.
Trying to execute it with exec() statement, but dont have any results
```
transaction(getSQLCon(159)) {
exec(
            """
                    declare @face_id int, @data smalldatetime,@sklad_id int
                    set @data=getdate()
                    exec p_sklad_show_siz_by_face @face_id,@data,@sklad_id
    """.trimIndent()
        )
{
            println(it.fetchSize)
            while (it.next()) {
                result.add(
                    Ppe(
                        it.getString("mat_nam"),
                        it.getString("edizm_abr"),
                        it.getInt("matnorm_kol"),
                        it.getInt("matvid_kol"),
                        it.getDate("docum_dat")?.toLocalDate().toString(),
                        it.getDate("vozvrat_dat")?.toLocalDate().toString(),
                        it.getInt("snkd_n")
                    )
                )
            }
            //   return@exec result//.toTypedArray()
        }
}
```
If i add selec 1 as mat_nam in the first row in exec() statement, i go to the { while (it.next()) ....} block.

In Transaction.kt on the row № 93 there is code 
```
        val result = when (type) {
                    StatementType.SELECT -> executeQuery()
                    else -> {
                        executeUpdate()
                        resultSet
                    }
                }
```
My query goes to else.
So to resolve it, i save procedure results to #table, and use second exec() where do select from that #table.

Maybe there is another way? thanks

**Comment by TemichCh** [comment] 2021-05-26 13:26
found this, it works. Thanks to vasily-kirichenko

https://github.com/JetBrains/Exposed/issues/390

**Comment by Tapac** [comment] 2021-06-04 17:14
Duplicate of #390

**Comment by Tapac** [comment] 2021-06-04 17:15
@TemichCh , please check https://github.com/JetBrains/Exposed/issues/390#issuecomment-854884236

**Closed by Tapac** 2021-06-04 17:15 UTC
